import Head from 'next/head';
import { Card } from '../components';
import { meta } from '../data/meta';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{meta.title}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

        <Card date="1.1.2002." subtitle="Tessa Sharpe" summary="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem like Aldus PageMaker including versions of Loremlike Aldus PageMaker including versions of Loremlike Aldus PageMaker including versions of Loremlike Aldus PageMaker including versions of Lorem" tag="Recenzija" title="The Girls I've been" />

      </main>

    </div>
  );
}
